version: '3.8'

services:
  flask_app:
    build: .
    container_name: flask_app
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - app_network
    mem_limit: 500MB
    cpus: "1.5"

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "d:/CompanyApps/Saas/MediaCutsVersions/MediaCutsStudioV3.0.0.0/Landingpage/nginx/conf/nginx.conf:/etc/nginx/nginx.conf"
      - d:/CompanyApps/Saas/MediaCutsVersions/MediaCutsStudioV3.0.0.0/Landingpage/nginx/certificados:/etc/nginx/certificados:ro  
    depends_on:
      - flask_app
    networks:
      - app_network
    mem_limit: 500MB
    cpus: "1.5"

networks:
  app_network:
    driver: bridge
